// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/req.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from src/req.proto</summary>
public static partial class ReqReflection {

  #region Descriptor
  /// <summary>File descriptor for src/req.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1zcmMvcmVxLnByb3RvInwKHFNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVS",
          "ZXESEgoKZGV2aWNlVHlwZRgBIAEoBRITCgtmaW5nZXJQcmludBgCIAEoCRIO",
          "CgZtb2JpbGUYAyABKAkSDgoGcmVzZW5kGAQgASgIEhMKC2xhc3RDaGFubmVs",
          "GAUgASgFIm8KCExvZ2luUmVxEhAKCGNsaWVudElkGAEgASgFEhIKCmRldmlj",
          "ZVR5cGUYAiABKAUSEwoLZmluZ2VyUHJpbnQYAyABKAkSDgoGbW9iaWxlGAQg",
          "ASgJEhgKEHZlcmlmaWNhdGlvbkNvZGUYBSABKAkiWAoMQXV0b0xvZ2luUmVx",
          "EhAKCGNsaWVudElkGAEgASgFEhIKCmRldmljZVR5cGUYAiABKAUSEwoLZmlu",
          "Z2VyUHJpbnQYAyABKAkSDQoFdG9rZW4YBCABKAlCKQonY29tLmxhd3NvZm5h",
          "dHVyZS5hcGlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SendLoginVerificationCodeReq), global::SendLoginVerificationCodeReq.Parser, new[]{ "DeviceType", "FingerPrint", "Mobile", "Resend", "LastChannel" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginReq), global::LoginReq.Parser, new[]{ "ClientId", "DeviceType", "FingerPrint", "Mobile", "VerificationCode" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AutoLoginReq), global::AutoLoginReq.Parser, new[]{ "ClientId", "DeviceType", "FingerPrint", "Token" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SendLoginVerificationCodeReq : pb::IMessage<SendLoginVerificationCodeReq> {
  private static readonly pb::MessageParser<SendLoginVerificationCodeReq> _parser = new pb::MessageParser<SendLoginVerificationCodeReq>(() => new SendLoginVerificationCodeReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SendLoginVerificationCodeReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq(SendLoginVerificationCodeReq other) : this() {
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    mobile_ = other.mobile_;
    resend_ = other.resend_;
    lastChannel_ = other.lastChannel_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq Clone() {
    return new SendLoginVerificationCodeReq(this);
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 1;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 2;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "mobile" field.</summary>
  public const int MobileFieldNumber = 3;
  private string mobile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mobile {
    get { return mobile_; }
    set {
      mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "resend" field.</summary>
  public const int ResendFieldNumber = 4;
  private bool resend_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Resend {
    get { return resend_; }
    set {
      resend_ = value;
    }
  }

  /// <summary>Field number for the "lastChannel" field.</summary>
  public const int LastChannelFieldNumber = 5;
  private int lastChannel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int LastChannel {
    get { return lastChannel_; }
    set {
      lastChannel_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SendLoginVerificationCodeReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SendLoginVerificationCodeReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Mobile != other.Mobile) return false;
    if (Resend != other.Resend) return false;
    if (LastChannel != other.LastChannel) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
    if (Resend != false) hash ^= Resend.GetHashCode();
    if (LastChannel != 0) hash ^= LastChannel.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (DeviceType != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FingerPrint);
    }
    if (Mobile.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Mobile);
    }
    if (Resend != false) {
      output.WriteRawTag(32);
      output.WriteBool(Resend);
    }
    if (LastChannel != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LastChannel);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Mobile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
    }
    if (Resend != false) {
      size += 1 + 1;
    }
    if (LastChannel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastChannel);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SendLoginVerificationCodeReq other) {
    if (other == null) {
      return;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Mobile.Length != 0) {
      Mobile = other.Mobile;
    }
    if (other.Resend != false) {
      Resend = other.Resend;
    }
    if (other.LastChannel != 0) {
      LastChannel = other.LastChannel;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 18: {
          FingerPrint = input.ReadString();
          break;
        }
        case 26: {
          Mobile = input.ReadString();
          break;
        }
        case 32: {
          Resend = input.ReadBool();
          break;
        }
        case 40: {
          LastChannel = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class LoginReq : pb::IMessage<LoginReq> {
  private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq(LoginReq other) : this() {
    clientId_ = other.clientId_;
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    mobile_ = other.mobile_;
    verificationCode_ = other.verificationCode_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq Clone() {
    return new LoginReq(this);
  }

  /// <summary>Field number for the "clientId" field.</summary>
  public const int ClientIdFieldNumber = 1;
  private int clientId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ClientId {
    get { return clientId_; }
    set {
      clientId_ = value;
    }
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 2;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 3;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "mobile" field.</summary>
  public const int MobileFieldNumber = 4;
  private string mobile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mobile {
    get { return mobile_; }
    set {
      mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "verificationCode" field.</summary>
  public const int VerificationCodeFieldNumber = 5;
  private string verificationCode_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string VerificationCode {
    get { return verificationCode_; }
    set {
      verificationCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as LoginReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(LoginReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientId != other.ClientId) return false;
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Mobile != other.Mobile) return false;
    if (VerificationCode != other.VerificationCode) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientId != 0) hash ^= ClientId.GetHashCode();
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
    if (VerificationCode.Length != 0) hash ^= VerificationCode.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ClientId);
    }
    if (DeviceType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FingerPrint);
    }
    if (Mobile.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Mobile);
    }
    if (VerificationCode.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(VerificationCode);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ClientId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
    }
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Mobile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
    }
    if (VerificationCode.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(VerificationCode);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(LoginReq other) {
    if (other == null) {
      return;
    }
    if (other.ClientId != 0) {
      ClientId = other.ClientId;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Mobile.Length != 0) {
      Mobile = other.Mobile;
    }
    if (other.VerificationCode.Length != 0) {
      VerificationCode = other.VerificationCode;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          ClientId = input.ReadInt32();
          break;
        }
        case 16: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 26: {
          FingerPrint = input.ReadString();
          break;
        }
        case 34: {
          Mobile = input.ReadString();
          break;
        }
        case 42: {
          VerificationCode = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class AutoLoginReq : pb::IMessage<AutoLoginReq> {
  private static readonly pb::MessageParser<AutoLoginReq> _parser = new pb::MessageParser<AutoLoginReq>(() => new AutoLoginReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AutoLoginReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq(AutoLoginReq other) : this() {
    clientId_ = other.clientId_;
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    token_ = other.token_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq Clone() {
    return new AutoLoginReq(this);
  }

  /// <summary>Field number for the "clientId" field.</summary>
  public const int ClientIdFieldNumber = 1;
  private int clientId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ClientId {
    get { return clientId_; }
    set {
      clientId_ = value;
    }
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 2;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 3;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 4;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AutoLoginReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AutoLoginReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientId != other.ClientId) return false;
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Token != other.Token) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientId != 0) hash ^= ClientId.GetHashCode();
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ClientId);
    }
    if (DeviceType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FingerPrint);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Token);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ClientId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
    }
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AutoLoginReq other) {
    if (other == null) {
      return;
    }
    if (other.ClientId != 0) {
      ClientId = other.ClientId;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          ClientId = input.ReadInt32();
          break;
        }
        case 16: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 26: {
          FingerPrint = input.ReadString();
          break;
        }
        case 34: {
          Token = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
