// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/req.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from src/req.proto</summary>
public static partial class ReqReflection {

  #region Descriptor
  /// <summary>File descriptor for src/req.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1zcmMvcmVxLnByb3RvIsIBChxTZW5kTG9naW5WZXJpZmljYXRpb25Db2Rl",
          "UmVxEhIKCmRldmljZVR5cGUYASABKAUSEwoLZmluZ2VyUHJpbnQYAiABKAkS",
          "DgoGbW9iaWxlGAMgASgJEg4KBnJlc2VuZBgEIAEoCBITCgtsYXN0Q2hhbm5l",
          "bBgFIAEoBRIMCgRleHQxGAYgASgJEgwKBGV4dDIYByABKAkSDAoEZXh0MxgI",
          "IAEoCRIMCgRleHQ0GAkgASgJEgwKBGV4dDUYCiABKAkitQEKCExvZ2luUmVx",
          "EhAKCGNsaWVudElkGAEgASgFEhIKCmRldmljZVR5cGUYAiABKAUSEwoLZmlu",
          "Z2VyUHJpbnQYAyABKAkSDgoGbW9iaWxlGAQgASgJEhgKEHZlcmlmaWNhdGlv",
          "bkNvZGUYBSABKAkSDAoEZXh0MRgGIAEoCRIMCgRleHQyGAcgASgJEgwKBGV4",
          "dDMYCCABKAkSDAoEZXh0NBgJIAEoCRIMCgRleHQ1GAogASgJIp4BCgxBdXRv",
          "TG9naW5SZXESEAoIY2xpZW50SWQYASABKAUSEgoKZGV2aWNlVHlwZRgCIAEo",
          "BRITCgtmaW5nZXJQcmludBgDIAEoCRINCgV0b2tlbhgEIAEoCRIMCgRleHQx",
          "GAUgASgJEgwKBGV4dDIYBiABKAkSDAoEZXh0MxgHIAEoCRIMCgRleHQ0GAgg",
          "ASgJEgwKBGV4dDUYCSABKAlCKQonY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRl",
          "d2F5LmRvbWFpbi5odHRwYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SendLoginVerificationCodeReq), global::SendLoginVerificationCodeReq.Parser, new[]{ "DeviceType", "FingerPrint", "Mobile", "Resend", "LastChannel", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginReq), global::LoginReq.Parser, new[]{ "ClientId", "DeviceType", "FingerPrint", "Mobile", "VerificationCode", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AutoLoginReq), global::AutoLoginReq.Parser, new[]{ "ClientId", "DeviceType", "FingerPrint", "Token", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SendLoginVerificationCodeReq : pb::IMessage<SendLoginVerificationCodeReq> {
  private static readonly pb::MessageParser<SendLoginVerificationCodeReq> _parser = new pb::MessageParser<SendLoginVerificationCodeReq>(() => new SendLoginVerificationCodeReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SendLoginVerificationCodeReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq(SendLoginVerificationCodeReq other) : this() {
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    mobile_ = other.mobile_;
    resend_ = other.resend_;
    lastChannel_ = other.lastChannel_;
    ext1_ = other.ext1_;
    ext2_ = other.ext2_;
    ext3_ = other.ext3_;
    ext4_ = other.ext4_;
    ext5_ = other.ext5_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SendLoginVerificationCodeReq Clone() {
    return new SendLoginVerificationCodeReq(this);
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 1;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 2;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "mobile" field.</summary>
  public const int MobileFieldNumber = 3;
  private string mobile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mobile {
    get { return mobile_; }
    set {
      mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "resend" field.</summary>
  public const int ResendFieldNumber = 4;
  private bool resend_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Resend {
    get { return resend_; }
    set {
      resend_ = value;
    }
  }

  /// <summary>Field number for the "lastChannel" field.</summary>
  public const int LastChannelFieldNumber = 5;
  private int lastChannel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int LastChannel {
    get { return lastChannel_; }
    set {
      lastChannel_ = value;
    }
  }

  /// <summary>Field number for the "ext1" field.</summary>
  public const int Ext1FieldNumber = 6;
  private string ext1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext1 {
    get { return ext1_; }
    set {
      ext1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext2" field.</summary>
  public const int Ext2FieldNumber = 7;
  private string ext2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext2 {
    get { return ext2_; }
    set {
      ext2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext3" field.</summary>
  public const int Ext3FieldNumber = 8;
  private string ext3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext3 {
    get { return ext3_; }
    set {
      ext3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext4" field.</summary>
  public const int Ext4FieldNumber = 9;
  private string ext4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext4 {
    get { return ext4_; }
    set {
      ext4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext5" field.</summary>
  public const int Ext5FieldNumber = 10;
  private string ext5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext5 {
    get { return ext5_; }
    set {
      ext5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SendLoginVerificationCodeReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SendLoginVerificationCodeReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Mobile != other.Mobile) return false;
    if (Resend != other.Resend) return false;
    if (LastChannel != other.LastChannel) return false;
    if (Ext1 != other.Ext1) return false;
    if (Ext2 != other.Ext2) return false;
    if (Ext3 != other.Ext3) return false;
    if (Ext4 != other.Ext4) return false;
    if (Ext5 != other.Ext5) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
    if (Resend != false) hash ^= Resend.GetHashCode();
    if (LastChannel != 0) hash ^= LastChannel.GetHashCode();
    if (Ext1.Length != 0) hash ^= Ext1.GetHashCode();
    if (Ext2.Length != 0) hash ^= Ext2.GetHashCode();
    if (Ext3.Length != 0) hash ^= Ext3.GetHashCode();
    if (Ext4.Length != 0) hash ^= Ext4.GetHashCode();
    if (Ext5.Length != 0) hash ^= Ext5.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (DeviceType != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FingerPrint);
    }
    if (Mobile.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Mobile);
    }
    if (Resend != false) {
      output.WriteRawTag(32);
      output.WriteBool(Resend);
    }
    if (LastChannel != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LastChannel);
    }
    if (Ext1.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Ext1);
    }
    if (Ext2.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Ext2);
    }
    if (Ext3.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Ext3);
    }
    if (Ext4.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Ext4);
    }
    if (Ext5.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Ext5);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Mobile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
    }
    if (Resend != false) {
      size += 1 + 1;
    }
    if (LastChannel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastChannel);
    }
    if (Ext1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext1);
    }
    if (Ext2.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext2);
    }
    if (Ext3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext3);
    }
    if (Ext4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext4);
    }
    if (Ext5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext5);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SendLoginVerificationCodeReq other) {
    if (other == null) {
      return;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Mobile.Length != 0) {
      Mobile = other.Mobile;
    }
    if (other.Resend != false) {
      Resend = other.Resend;
    }
    if (other.LastChannel != 0) {
      LastChannel = other.LastChannel;
    }
    if (other.Ext1.Length != 0) {
      Ext1 = other.Ext1;
    }
    if (other.Ext2.Length != 0) {
      Ext2 = other.Ext2;
    }
    if (other.Ext3.Length != 0) {
      Ext3 = other.Ext3;
    }
    if (other.Ext4.Length != 0) {
      Ext4 = other.Ext4;
    }
    if (other.Ext5.Length != 0) {
      Ext5 = other.Ext5;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 18: {
          FingerPrint = input.ReadString();
          break;
        }
        case 26: {
          Mobile = input.ReadString();
          break;
        }
        case 32: {
          Resend = input.ReadBool();
          break;
        }
        case 40: {
          LastChannel = input.ReadInt32();
          break;
        }
        case 50: {
          Ext1 = input.ReadString();
          break;
        }
        case 58: {
          Ext2 = input.ReadString();
          break;
        }
        case 66: {
          Ext3 = input.ReadString();
          break;
        }
        case 74: {
          Ext4 = input.ReadString();
          break;
        }
        case 82: {
          Ext5 = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class LoginReq : pb::IMessage<LoginReq> {
  private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq(LoginReq other) : this() {
    clientId_ = other.clientId_;
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    mobile_ = other.mobile_;
    verificationCode_ = other.verificationCode_;
    ext1_ = other.ext1_;
    ext2_ = other.ext2_;
    ext3_ = other.ext3_;
    ext4_ = other.ext4_;
    ext5_ = other.ext5_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginReq Clone() {
    return new LoginReq(this);
  }

  /// <summary>Field number for the "clientId" field.</summary>
  public const int ClientIdFieldNumber = 1;
  private int clientId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ClientId {
    get { return clientId_; }
    set {
      clientId_ = value;
    }
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 2;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 3;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "mobile" field.</summary>
  public const int MobileFieldNumber = 4;
  private string mobile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mobile {
    get { return mobile_; }
    set {
      mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "verificationCode" field.</summary>
  public const int VerificationCodeFieldNumber = 5;
  private string verificationCode_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string VerificationCode {
    get { return verificationCode_; }
    set {
      verificationCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext1" field.</summary>
  public const int Ext1FieldNumber = 6;
  private string ext1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext1 {
    get { return ext1_; }
    set {
      ext1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext2" field.</summary>
  public const int Ext2FieldNumber = 7;
  private string ext2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext2 {
    get { return ext2_; }
    set {
      ext2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext3" field.</summary>
  public const int Ext3FieldNumber = 8;
  private string ext3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext3 {
    get { return ext3_; }
    set {
      ext3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext4" field.</summary>
  public const int Ext4FieldNumber = 9;
  private string ext4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext4 {
    get { return ext4_; }
    set {
      ext4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext5" field.</summary>
  public const int Ext5FieldNumber = 10;
  private string ext5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext5 {
    get { return ext5_; }
    set {
      ext5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as LoginReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(LoginReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientId != other.ClientId) return false;
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Mobile != other.Mobile) return false;
    if (VerificationCode != other.VerificationCode) return false;
    if (Ext1 != other.Ext1) return false;
    if (Ext2 != other.Ext2) return false;
    if (Ext3 != other.Ext3) return false;
    if (Ext4 != other.Ext4) return false;
    if (Ext5 != other.Ext5) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientId != 0) hash ^= ClientId.GetHashCode();
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
    if (VerificationCode.Length != 0) hash ^= VerificationCode.GetHashCode();
    if (Ext1.Length != 0) hash ^= Ext1.GetHashCode();
    if (Ext2.Length != 0) hash ^= Ext2.GetHashCode();
    if (Ext3.Length != 0) hash ^= Ext3.GetHashCode();
    if (Ext4.Length != 0) hash ^= Ext4.GetHashCode();
    if (Ext5.Length != 0) hash ^= Ext5.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ClientId);
    }
    if (DeviceType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FingerPrint);
    }
    if (Mobile.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Mobile);
    }
    if (VerificationCode.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(VerificationCode);
    }
    if (Ext1.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Ext1);
    }
    if (Ext2.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Ext2);
    }
    if (Ext3.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Ext3);
    }
    if (Ext4.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Ext4);
    }
    if (Ext5.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Ext5);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ClientId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
    }
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Mobile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
    }
    if (VerificationCode.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(VerificationCode);
    }
    if (Ext1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext1);
    }
    if (Ext2.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext2);
    }
    if (Ext3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext3);
    }
    if (Ext4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext4);
    }
    if (Ext5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext5);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(LoginReq other) {
    if (other == null) {
      return;
    }
    if (other.ClientId != 0) {
      ClientId = other.ClientId;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Mobile.Length != 0) {
      Mobile = other.Mobile;
    }
    if (other.VerificationCode.Length != 0) {
      VerificationCode = other.VerificationCode;
    }
    if (other.Ext1.Length != 0) {
      Ext1 = other.Ext1;
    }
    if (other.Ext2.Length != 0) {
      Ext2 = other.Ext2;
    }
    if (other.Ext3.Length != 0) {
      Ext3 = other.Ext3;
    }
    if (other.Ext4.Length != 0) {
      Ext4 = other.Ext4;
    }
    if (other.Ext5.Length != 0) {
      Ext5 = other.Ext5;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          ClientId = input.ReadInt32();
          break;
        }
        case 16: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 26: {
          FingerPrint = input.ReadString();
          break;
        }
        case 34: {
          Mobile = input.ReadString();
          break;
        }
        case 42: {
          VerificationCode = input.ReadString();
          break;
        }
        case 50: {
          Ext1 = input.ReadString();
          break;
        }
        case 58: {
          Ext2 = input.ReadString();
          break;
        }
        case 66: {
          Ext3 = input.ReadString();
          break;
        }
        case 74: {
          Ext4 = input.ReadString();
          break;
        }
        case 82: {
          Ext5 = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class AutoLoginReq : pb::IMessage<AutoLoginReq> {
  private static readonly pb::MessageParser<AutoLoginReq> _parser = new pb::MessageParser<AutoLoginReq>(() => new AutoLoginReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AutoLoginReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ReqReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq(AutoLoginReq other) : this() {
    clientId_ = other.clientId_;
    deviceType_ = other.deviceType_;
    fingerPrint_ = other.fingerPrint_;
    token_ = other.token_;
    ext1_ = other.ext1_;
    ext2_ = other.ext2_;
    ext3_ = other.ext3_;
    ext4_ = other.ext4_;
    ext5_ = other.ext5_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AutoLoginReq Clone() {
    return new AutoLoginReq(this);
  }

  /// <summary>Field number for the "clientId" field.</summary>
  public const int ClientIdFieldNumber = 1;
  private int clientId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ClientId {
    get { return clientId_; }
    set {
      clientId_ = value;
    }
  }

  /// <summary>Field number for the "deviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 2;
  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = value;
    }
  }

  /// <summary>Field number for the "fingerPrint" field.</summary>
  public const int FingerPrintFieldNumber = 3;
  private string fingerPrint_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FingerPrint {
    get { return fingerPrint_; }
    set {
      fingerPrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 4;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext1" field.</summary>
  public const int Ext1FieldNumber = 5;
  private string ext1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext1 {
    get { return ext1_; }
    set {
      ext1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext2" field.</summary>
  public const int Ext2FieldNumber = 6;
  private string ext2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext2 {
    get { return ext2_; }
    set {
      ext2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext3" field.</summary>
  public const int Ext3FieldNumber = 7;
  private string ext3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext3 {
    get { return ext3_; }
    set {
      ext3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext4" field.</summary>
  public const int Ext4FieldNumber = 8;
  private string ext4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext4 {
    get { return ext4_; }
    set {
      ext4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext5" field.</summary>
  public const int Ext5FieldNumber = 9;
  private string ext5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext5 {
    get { return ext5_; }
    set {
      ext5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AutoLoginReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AutoLoginReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientId != other.ClientId) return false;
    if (DeviceType != other.DeviceType) return false;
    if (FingerPrint != other.FingerPrint) return false;
    if (Token != other.Token) return false;
    if (Ext1 != other.Ext1) return false;
    if (Ext2 != other.Ext2) return false;
    if (Ext3 != other.Ext3) return false;
    if (Ext4 != other.Ext4) return false;
    if (Ext5 != other.Ext5) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientId != 0) hash ^= ClientId.GetHashCode();
    if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
    if (FingerPrint.Length != 0) hash ^= FingerPrint.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (Ext1.Length != 0) hash ^= Ext1.GetHashCode();
    if (Ext2.Length != 0) hash ^= Ext2.GetHashCode();
    if (Ext3.Length != 0) hash ^= Ext3.GetHashCode();
    if (Ext4.Length != 0) hash ^= Ext4.GetHashCode();
    if (Ext5.Length != 0) hash ^= Ext5.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ClientId);
    }
    if (DeviceType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FingerPrint);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Token);
    }
    if (Ext1.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Ext1);
    }
    if (Ext2.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Ext2);
    }
    if (Ext3.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Ext3);
    }
    if (Ext4.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Ext4);
    }
    if (Ext5.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Ext5);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ClientId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
    }
    if (DeviceType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (FingerPrint.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FingerPrint);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (Ext1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext1);
    }
    if (Ext2.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext2);
    }
    if (Ext3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext3);
    }
    if (Ext4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext4);
    }
    if (Ext5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext5);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AutoLoginReq other) {
    if (other == null) {
      return;
    }
    if (other.ClientId != 0) {
      ClientId = other.ClientId;
    }
    if (other.DeviceType != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.FingerPrint.Length != 0) {
      FingerPrint = other.FingerPrint;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    if (other.Ext1.Length != 0) {
      Ext1 = other.Ext1;
    }
    if (other.Ext2.Length != 0) {
      Ext2 = other.Ext2;
    }
    if (other.Ext3.Length != 0) {
      Ext3 = other.Ext3;
    }
    if (other.Ext4.Length != 0) {
      Ext4 = other.Ext4;
    }
    if (other.Ext5.Length != 0) {
      Ext5 = other.Ext5;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          ClientId = input.ReadInt32();
          break;
        }
        case 16: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 26: {
          FingerPrint = input.ReadString();
          break;
        }
        case 34: {
          Token = input.ReadString();
          break;
        }
        case 42: {
          Ext1 = input.ReadString();
          break;
        }
        case 50: {
          Ext2 = input.ReadString();
          break;
        }
        case 58: {
          Ext3 = input.ReadString();
          break;
        }
        case 66: {
          Ext4 = input.ReadString();
          break;
        }
        case 74: {
          Ext5 = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
